PHONE_NUMBER_FIELD = 'phone_number'
OTP_FIELD = 'otp'
OTP_HASH_FIELD = 'otp_hash'
ID_KEY_FIELD = 'id_key'
ONETIME_KEYS_FIELD = 'one_time_keys'

STATUS_FIELD = 'status'
ERROR_FIELD = 'error'

STATUS_OK = 'ok'
STATUS_OK_RESPONSE = {STATUS_FIELD: STATUS_OK}
UNSPECIFIED_ERROR = 'Unspecified'

API_ENDPOINT_ROOT = "/"
API_ENDPOINT_REGISTER_NUMBER = "/register/number"
API_ENDPOINT_REGISTER_VALIDATE = "/register/validate"
API_ENDPOINT_USER_KEYS = "/usr/keys"

MAX_USERS = 10
MAX_MSGS = 2
